### PR TITLE
Fix pip install with missing parse_requirements

### LINKED ISSUE #62: pip3 installation error
```
root@netbox:/opt/netbox# pip3 install napalm-ros
Collecting napalm-ros
  Using cached https://files.pythonhosted.org/packages/5e/66/d3eac865f5f6622ff05139545541e2a9be89734f113831730c67d45e1eb2/napalm-ros-0.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-h84tbfn1/napalm-ros/setup.py", line 6, in <module>
        from pip.req import parse_requirements
    ImportError: No module named 'pip.req'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-h84tbfn1/napalm-ros/

```

Errors when installing on Ubuntu 18.04

### PR DESCRIPTION
**Pull request by luqasz**
closes #62

### CODE REVIEW

**Comment by luqasz** [comment]
@ktbyers Do you have any workaround for failing travis test result when upload to pypi fails ? Like [this](https://travis-ci.org/napalm-automation-community/napalm-ros/jobs/388204397) one.

**Comment by ktbyers** [comment]
I am a bit out of the loop on that. The main differences I see comparing between what you have and what napalm main has is that we are calling all of our testing via `tox`.

I would also add a develop branch and then merge PRs into the develop branch and then only merge into master on the release (but that doesn't explain why you had that issue with this branch since it was not on master).

You might ask Patrick Ogenstad. He does a lot of work here and is very good with the tool chains.

**Comment by ktbyers** [comment]
I am a bit out of the loop on that. The main differences I see comparing between what you have and what napalm main has is that we are calling all of our testing via `tox`.

I would also add a develop branch and then merge PRs into the develop branch and then only merge into master on the release (but that doesn't explain why you had that issue with this branch since it was not on master).

You might ask Patrick Ogenstad. He does a lot of work here and is very good with the tool chains.

**Comment by ktbyers** [comment]
What was the purpose of the subprocess change?

**Comment by luqasz** [comment]
> What was the purpose of the subprocess change?

For setup.py to always get version from git tags. I forget to bump version in setup.py when I add a newer tag.

**Comment by luqasz** [comment]
> I am a bit out of the loop on that. The main differences I see comparing between what you have and what napalm main has is that we are calling all of our testing via tox.

> I would also add a develop branch and then merge PRs into the develop branch and then only merge into master on the release (but that doesn't explain why you had that issue with this branch since it was not on master).

> You might ask Patrick Ogenstad. He does a lot of work here and is very good with the tool chains.

summon @ogenstad

**Comment by ogenstad** [comment]
Summoned. Sounds like jury duty or something...

I’m on the bus on the way home having been out drinking beer, so I might be missing something. But I don’t see how that sub process thing would work. When people are downloading the package and install it they will have to run the same code and they won’t have access to any git repo. To me it looks like something that will only work in development.

**Comment by luqasz** [comment]
I'd like to have some tool / code so that when I tag commit with a newer version, version in setup.py will be updated.

**Pull request merged**
