### PR TITLE
 Add get_ntp_peers method

### PR DESCRIPTION
**Pull request by luqasz**

### CODE REVIEW

**Comment by dbarrosop** [comment]
ready to merge?

**Comment by luqasz** [comment]
Does `get_ntp_peers()` refer to peers that router connects to or peers that are connected to router. In other words. Should this method return peers that are connected to NTP server on a router ?

**Comment by dbarrosop** [comment]
@mirceaulinic could you clarify that question, please?

**Comment by luqasz** [comment]
@mirceaulinic bump.

**Comment by mirceaulinic** [comment]
Hi @luqasz - apologies for late reply. In general the difference as I will explain below, but I am not absolutely sure ROS or other platforms respect this.
When you configure a NTP server the device will sync with the remote server you configure. This is unidirectional.
Peers, on the other hand, exchange the timestamps between themselves, which is bidirectional.
Have I answered your question?

**Comment by luqasz** [comment]
Ah. Now I get the picture.
> Peers, on the other hand, exchange the timestamps between themselves, which is bidirectional.

I am curious where is this used ? A use case scenario. I ask because I so not understand this mechanism. I am only aware of NTP server and client modes.

**Pull request closed without merging**
