### PR TITLE
Improve the SSH based get_config() method

### PR DESCRIPTION
**Pull request by washcroft**
**Improve the SSH based get_config() method:**
- Remove always changing date/time from first line of config - helpful if feeding into a differential config backup system)
- New optional_arg **ssh_port** - set to override the default port 22 when connecting via SSH

### CODE REVIEW

**Comment by luqasz** [comment]
Split this into separate pull requests.
Make sure code is formatted.
Make sure tests pass.

**Comment by washcroft** [comment]
Done

**Comment by luqasz** [comment]
Please rebase/merge newest master. I've added get_config tests.

**Comment by washcroft** [comment]
> Please rebase/merge newest master. I've added get_config tests.

Done

**Comment by luqasz** [comment]
I've forgot to merge my get_config tests branch. Please rebase. Sorry for inconvenience.

**Comment by washcroft** [comment]
> I've forgot to merge my get_config tests branch. Please rebase. Sorry for inconvenience.

No problem, done.

**Review by luqasz — APPROVED** [review]

**Pull request merged**
