### PR TITLE
get_ipv6_neighbors_table()

### PR DESCRIPTION
**Pull request by pierky**
Implements https://github.com/napalm-automation/napalm-base/pull/311

### CODE REVIEW

**Comment by luqasz** [comment]
For tests to work, `napalm-base` needs to be released with this method.

**Comment by dbarrosop** [comment]
Just FYI, `napalm-base` is dead. This should probably be adapted to the new `napalm` organization which should be actually quite easy (just changing a few imports should do).

**Comment by luqasz** [comment]
@pierky please rebase with newest master

**Comment by pierky** [comment]
Will do ASAP.

**Pull request merged**
